/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_stm32f4.h"
#include "led.h"
#include "push_button.h"

int main(void)
{
    //Inicializamos el sistema GPIO 
	gpio_init();

	//Inicializamos el led en pin 5 y boton en pin 13
	led_init();
	button_init();

	while (1)
	{
		if (button_get_state() == 1)
		{
			led_toggle();
		}
	}

	return 0;
}
